version: '3.3'

services:

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_USER=cooper
      - MYSQL_PASSWORD=cooper12345
      - MYSQL_ROOT_PASSWORD=cooper12345
      - MYSQL_DATABASE=contracts
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - app_network

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "9001:80"
    environment:
      - PMA_HOST=mysql
      - PHP_UPLOAD_MAX_FILESIZE=100M
      - PHP_POST_MAX_SIZE=100M
    depends_on:
      - mysql
    networks:
      - app_network    

  frontend:
    image: coopercar/contract_frontend:1.0
    ports:
      - "8080:80"
    environment:
      - TZ=Asia/Taipei
    networks:
      - app_network

  backend:
    image: coopercar/contract_backend:1.0
    ports:
      - "3000:3000"
    environment:
      - TZ=Asia/Taipei
    networks:
      - app_network
    depends_on:
      - mysql

networks:
  app_network:
    driver: bridge

volumes:
  mysql: